# Generated by Django 4.0.4 on 2022-07-04 12:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('last_name', models.CharField(blank=True, max_length=155)),
                ('phone', models.CharField(max_length=155)),
                ('email', models.CharField(max_length=155)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2022, 7, 4, 12, 26, 1, 309866, tzinfo=utc))),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book.category')),
            ],
        ),
    ]
